---
title: "課堂練習1"
date: "10/3/2018"
output: html_document
params:
  studentID: "410773072"
  studentName: "張翊宣"
---
存檔時，請用你的學號當延伸檔名。例如：若你的學號為41078392，則請`File->Save As...`存成Exercise1-41078392.Rmd。

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval = F)
```


## 1
引入[五大銀行一個月定存固定利率歷史月資料](https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv)。

```{r}
library(readr)
bankdata <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv")
```

### 1.1
將**銀行**變數改成factor
```{r q1-1}
as.factor(bankdata$銀行)
```

### 1.2
將**年月**改成西元年月
```{r q1-2}
str_c("0",bankdata$年月,'/01')->民國年月日
library(lubridate)
ymd(民國年月日)->民國年月日1
str_c(民國年月日1 + years(1911))->西元年月日
format(as.POSIXct(西元年月日),format=" %Y/%m")->西元年月
西元年月
```

```{r q1-2 answer2}
str_c("0",bankdata$年月,'/01')->民國年月日
library(lubridate)
ymd(民國年月日)->民國年月日1
str_c(民國年月日1 + years(1911))->西元年月日
as.factor(西元年月日)->西元年月日
str_replace(西元年月日,"-01","")->西元年月
西元年月
```

## 2
Google天災地圖會發佈天災時地資訊，如[潭美颱風(Typhoon Trami)](https://google.org/crisismap/google.com/2018-trami)，但它的時間是以UTC表示，如"2018/30/09 00:00 UTC",試透過`lubridate::with_tz()`將它轉成台灣時間
(Hint: 台灣tzone為"Asia/Taipei",它可用`grep("Taipei",OlsonNames(),value=TRUE)`指令查得)

```{r q2}

x <- ydm_hms("2018-30-09 00:00:00", tz = "UTC")
with_tz(x, "Asia/Taipei") #將UTC時間轉換成台北時間

```
```{r}
grep("Taipei",OlsonNames(),value=TRUE)
```



